version = 0.1
[default.deploy.parameters]
stack_name = "badminton-recharging"
resolve_s3 = true
s3_prefix = "badminton-recharging"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
